project:
  type: website
  output-dir: docs

website:
  title: "My example website"
  navbar:
    left:
      - href: index.qmd
        text: Homepage
      - about.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Assignments"
        contents:
          - href: ae01-unvotes.qmd
            text: "AE 01"


format:
  html:
    theme:
      light: sandstone
      dark: slate
    css: styles.css
    toc: true



